spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: "{cipher}607aa8ab39fcfa35ce73b13be823b9e08f5c3758c24667309cd68f79f4dc4541"

jwt:
  expiration_time: 1
  secret: ecommerce_token_default_changed

gateway:
  ip: localhost
